/**
 * The Revamp Radar UI kit: components from Magic UI (https://magicui.design) and Smooth UI (https://smoothui.dev),
 * ported from their React + Tailwind + Motion sources to plain CSS and JavaScript so they run inside the static,
 * CSP-locked redesign pages (no React, no build step, no extra script host). Both libraries are MIT licensed; see
 * THIRD_PARTY_NOTICES.md. Two more effects follow popular 21st.dev community components (scroll media expansion,
 * background paths); they are written from the components' descriptions, not their code.
 *
 * Every component takes its colours from the theme variables (--gold, --accent-rgb, ...), keeps the page's own text
 * untouched (effects only wrap or animate it), uses the individual `translate` property where it moves things so it
 * never fights the Motion script's transforms, sets starting states in script, and turns itself off (or into a
 * plain fade) under prefers-reduced-motion. Hover effects only run on devices with a fine pointer.
 *
 * Every redesign page ships with UI_KIT_CSS and UI_KIT_JS. The skill's references/ui-kit.md (generated by
 * `npm run skill:catalog`) tells Claude how to use each one.
 */

export interface KitComponent {
  id: string;
  name: string;
  library: "Magic UI" | "Smooth UI" | "21st.dev";
  /** What it is for in a redesign, and where not to use it. */
  use: string;
  /** Minimal markup. */
  markup: string;
}

export const UI_KIT: KitComponent[] = [
  // Magic UI
  {
    id: "marquee", name: "Marquee", library: "Magic UI",
    use: "An endless, pausable strip of the business's own photos, logos (brands stocked, partners, certifications) or short real labels such as service names. data-reverse flips it; data-repeat (default 4) sets copies. No ids inside the track: it is cloned.",
    markup: `<div class="mu-marquee" style="--duration:40s;--gap:2.5rem"><div class="mu-marquee-track"><img src="..." alt="..."> <img src="..." alt="..."></div></div>`,
  },
  {
    id: "border-beam", name: "Border Beam", library: "Magic UI",
    use: "A spark of light that travels around a box's border: the opening-hours card, a booking box or the main offer. One per page at most. Options: --beam-size, --beam-duration.",
    markup: `<div class="mu-beam" style="border-radius:4px">...</div>`,
  },
  {
    id: "shine-border", name: "Shine Border", library: "Magic UI",
    use: "A slow, shimmering gradient border: price cards, the visit box, a featured quote. Options: --shine-width, --shine-duration.",
    markup: `<div class="mu-shine">...</div>`,
  },
  {
    id: "shimmer-button", name: "Shimmer Button", library: "Magic UI",
    use: "A light that runs around a button's outline. Only the page's primary call to action (on .btn.gold).",
    markup: `<a class="btn gold mu-shimmer" href="...">Book a table</a>`,
  },
  {
    id: "animated-shiny-text", name: "Animated Shiny Text", library: "Magic UI",
    use: "A light sweep across a short line: the small \"Discover\" label or a one-line tagline. Never on body text.",
    markup: `<span class="mu-shiny">Welcome to</span>`,
  },
  {
    id: "magic-card", name: "Magic Card (spotlight)", library: "Magic UI",
    use: "A soft accent spotlight that follows the pointer over a card: dish cards, team, service or page cards. Option: --spot-size.",
    markup: `<a class="dish-card mu-spotlight" href="...">...</a>`,
  },
  {
    id: "number-ticker", name: "Number Ticker", library: "Magic UI",
    use: "Counts up to a number already in the site's text when it scrolls into view (\"Since 1987\", \"25 years\"); the final text is exactly the original. Only on elements with text and no child elements. Never for invented figures. data-start sets the start value (e.g. 1950 for a year), data-duration the seconds.",
    markup: `<span data-mu-ticker data-start="1950">Since 1987</span>`,
  },
  {
    id: "blur-fade", name: "Blur Fade", library: "Magic UI",
    use: "Fades and un-blurs an element in when it scrolls into view. For content the motion script does not already animate (not .hero/.page-top content, .echo, .zig, .info). data-delay (s), data-direction (up|down|left|right), data-offset (px).",
    markup: `<div data-mu-blur-fade data-delay="0.1">...</div>`,
  },
  {
    id: "dot-pattern", name: "Dot Pattern", library: "Magic UI",
    use: "A faint dot grid behind a section, fading out towards the edges. Put it first inside a position:relative container.",
    markup: `<section style="position:relative"><div class="mu-dots" aria-hidden="true"></div>...</section>`,
  },
  {
    id: "scroll-progress", name: "Scroll Progress", library: "Magic UI",
    use: "A hairline accent bar at the top of the window showing how far down the page you are. Once per page, right after <body>.",
    markup: `<div class="mu-progress" aria-hidden="true"></div>`,
  },
  // Smooth UI
  {
    id: "magnetic-button", name: "Magnetic Button", library: "Smooth UI",
    use: "The button leans towards the pointer as it approaches. Hero and call-to-action buttons. data-strength (default 0.25), data-radius (px, default 100). Not on .page-top .btn (the motion script moves those).",
    markup: `<a class="btn gold" data-su-magnetic href="...">Order online</a>`,
  },
  {
    id: "tilt-card", name: "Tilt Card", library: "Smooth UI",
    use: "A card that tilts in 3D towards the pointer with a soft glare. Photo cards and featured items. data-tilt-max (degrees, default 8); children with data-tilt-depth=\"0..1\" float with parallax.",
    markup: `<div class="dish-card" data-su-tilt data-tilt-max="6">...</div>`,
  },
  {
    id: "glow-hover-card", name: "Glow Hover Cards", library: "Smooth UI",
    use: "On a grid: every card's border lights up where the pointer is, across the whole grid. Option: --glow-size.",
    markup: `<div class="cards" data-su-glow><a class="dish-card">...</a><a class="dish-card">...</a></div>`,
  },
  {
    id: "mask-reveal-up", name: "Mask Reveal Up", library: "Smooth UI",
    use: "Each line of a heading rises out of a mask when it scrolls into view; <br> separates lines. Section headings that are not .echo headings, and short statements. data-delay (s), data-stagger (ms, default 90).",
    markup: `<h2 data-su-mask-reveal>Fresh every<br>morning</h2>`,
  },
  {
    id: "shimmer-sweep", name: "Shimmer Sweep", library: "Smooth UI",
    use: "A word or short line slides in from the left out of a blur when it scrolls into view. Labels, prices, small captions. data-delay (s).",
    markup: `<span data-su-sweep>Discover</span>`,
  },
  {
    id: "scroll-reveal-paragraph", name: "Scroll Reveal Paragraph", library: "Smooth UI",
    use: "The words of a paragraph light up one by one as you scroll through it. One strong paragraph per page (the story); never long lists or menus.",
    markup: `<p data-su-scroll-reveal>...</p>`,
  },

  // 21st.dev community (written from the components' descriptions; the source needs a 21st.dev account)
  {
    id: "scroll-expand-media", name: "Scroll Media Expansion", library: "21st.dev",
    use: "A framed photo opens up to full width as it scrolls into view (after 21st.dev's scroll-expansion hero). One per page, for the business's best wide photo: the dining room, the clinic, the workshop. Not inside .hero or the cloud reveal.",
    markup: `<div class="tw-expand"><div class="tw-expand-frame"><img src="..." alt="..." loading="lazy" referrerpolicy="no-referrer"></div></div>`,
  },
  {
    id: "background-paths", name: "Background Paths", library: "21st.dev",
    use: "Fine lines in the theme's accent that drift slowly behind a calm band (after 21st.dev's background paths): the footer call-to-action band, a quiet intro or quote section. Never behind photos or long text. Option: data-lines (default 18).",
    markup: `<div class="foot-cta"><div class="tw-paths" aria-hidden="true"></div> ...the band's content... </div>`,
  },
];

const MASK_RING = "-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask:linear-gradient(#000 0 0) content-box exclude,linear-gradient(#000 0 0)";

export const UI_KIT_CSS = `
/* UI kit: Magic UI + Smooth UI components (MIT), ported to plain CSS/JS */
/* Magic UI · Marquee */
.mu-marquee{--gap:2.5rem;--duration:40s;display:flex;gap:var(--gap);overflow:hidden;-webkit-mask-image:linear-gradient(90deg,transparent,#000 8%,#000 92%,transparent);mask-image:linear-gradient(90deg,transparent,#000 8%,#000 92%,transparent)}
.mu-marquee-track{display:flex;flex-shrink:0;align-items:center;justify-content:space-around;gap:var(--gap);min-width:100%}
.mu-marquee-track img{height:clamp(120px,18vw,220px);width:auto;object-fit:cover}
.mu-marquee.is-ready .mu-marquee-track{animation:mu-marquee var(--duration) linear infinite}
.mu-marquee[data-reverse] .mu-marquee-track{animation-direction:reverse}
.mu-marquee:hover .mu-marquee-track{animation-play-state:paused}
@keyframes mu-marquee{to{transform:translateX(calc(-100% - var(--gap)))}}
/* Magic UI · Border Beam */
.mu-beam,.mu-shine{position:relative}
.mu-beam-ray,.mu-shine-ray{position:absolute;inset:0;border-radius:inherit;pointer-events:none;${MASK_RING}}
.mu-beam-ray{display:none;padding:var(--beam-width,1px)}
@supports (offset-path:rect(0 auto auto 0)){.mu-beam-ray{display:block}}
.mu-beam-ray::before{content:"";position:absolute;width:var(--beam-size,90px);aspect-ratio:1;background:linear-gradient(to left,var(--gold-2),var(--gold),transparent);offset-path:rect(0 auto auto 0 round var(--beam-size,90px));animation:mu-beam var(--beam-duration,8s) linear infinite}
@keyframes mu-beam{from{offset-distance:0%}to{offset-distance:100%}}
/* Magic UI · Shine Border */
.mu-shine-ray{padding:var(--shine-width,1px);background-image:radial-gradient(transparent,transparent,var(--gold),var(--gold-2),transparent,transparent);background-size:300% 300%;animation:mu-shine var(--shine-duration,14s) linear infinite}
@keyframes mu-shine{0%{background-position:0% 0%}50%{background-position:100% 100%}to{background-position:0% 0%}}
/* Magic UI · Shimmer Button */
@property --mu-angle{syntax:"<angle>";inherits:false;initial-value:0deg}
.mu-shimmer{box-shadow:inset 0 -8px 10px rgba(var(--accent2-rgb),.1);transition:color .35s,border-color .35s,box-shadow .3s}
.mu-shimmer:hover{box-shadow:inset 0 -6px 10px rgba(var(--accent2-rgb),.25)}
.mu-shimmer::after{content:"";position:absolute;inset:0;padding:1px;pointer-events:none;background:conic-gradient(from var(--mu-angle),transparent 0 290deg,var(--gold-2) 345deg,transparent 360deg);${MASK_RING};animation:mu-spin 3s linear infinite}
@keyframes mu-spin{to{--mu-angle:360deg}}
/* Magic UI · Animated Shiny Text */
.mu-shiny{--shiny-width:120px;color:rgba(var(--ink-rgb),.62);background:linear-gradient(90deg,transparent,rgba(var(--accent2-rgb),.95) 50%,transparent) 0 0/var(--shiny-width) 100% no-repeat;-webkit-background-clip:text;background-clip:text;animation:mu-shiny 8s infinite}
@keyframes mu-shiny{0%,90%,to{background-position:calc(-100% - var(--shiny-width)) 0}30%,60%{background-position:calc(100% + var(--shiny-width)) 0}}
/* Magic UI · Magic Card (spotlight) */
.mu-spot{position:absolute;inset:0;border-radius:inherit;pointer-events:none;opacity:0;transition:opacity .45s;background:radial-gradient(var(--spot-size,260px) circle at var(--mx,-999px) var(--my,-999px),rgba(var(--accent-rgb),.14),transparent 100%)}
.is-lit>.mu-spot{opacity:1}
/* Magic UI · Dot Pattern */
.mu-dots{position:absolute;inset:0;z-index:0;pointer-events:none;background-image:radial-gradient(rgba(var(--ink-rgb),.16) 1px,transparent 1.5px);background-size:18px 18px;-webkit-mask-image:radial-gradient(ellipse at center,#000 30%,transparent 75%);mask-image:radial-gradient(ellipse at center,#000 30%,transparent 75%)}
/* Magic UI · Scroll Progress */
.mu-progress{position:fixed;inset:0 0 auto;z-index:60;height:2px;transform:scaleX(0);transform-origin:left;background:linear-gradient(90deg,var(--gold),var(--gold-2));pointer-events:none}
/* Smooth UI · Tilt Card, Glow Hover Cards, Mask Reveal Up, Scroll Reveal Paragraph */
.su-glare{position:absolute;inset:0;border-radius:inherit;pointer-events:none;opacity:0;transition:opacity .3s}
.su-glow-ray{position:absolute;inset:0;border-radius:inherit;pointer-events:none;padding:1px;background:radial-gradient(var(--glow-size,320px) circle at var(--gx,-999px) var(--gy,-999px),rgba(var(--accent2-rgb),.9),transparent 60%);${MASK_RING};opacity:var(--glow-on,0);transition:opacity .4s}
.su-mask{display:block;overflow:hidden;padding-bottom:.08em}
.su-mask-in{display:block}
.su-word{transition:opacity .15s linear}
/* 21st.dev-style · Scroll Media Expansion */
.tw-expand-frame{overflow:hidden;aspect-ratio:16/8}
.tw-expand-frame img{width:100%;height:100%;object-fit:cover}
@media (max-width:760px){.tw-expand-frame{aspect-ratio:4/5}}
/* 21st.dev-style · Background Paths */
.tw-paths{position:absolute;inset:0;overflow:hidden;pointer-events:none;z-index:0}
.tw-paths~*{position:relative;z-index:1}
.tw-paths svg{width:100%;height:100%;display:block}
.tw-paths path{fill:none;stroke:rgb(var(--accent-rgb));stroke-linecap:round;animation:tw-path var(--d,24s) linear infinite}
@keyframes tw-path{to{stroke-dashoffset:-1000}}
@media (prefers-reduced-motion:reduce){
  .tw-paths path{animation:none}
  .mu-beam-ray,.mu-shine-ray{display:none}
  .mu-shimmer::after{animation:none;opacity:0}
  .mu-shiny{animation:none;background:none;color:inherit}
  .mu-marquee{overflow-x:auto}
  .mu-marquee .mu-marquee-track{animation:none}
}
`;

export const UI_KIT_JS = `(function(){
  var reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;
  var hover = matchMedia('(hover: hover) and (pointer: fine)').matches;
  var io = 'IntersectionObserver' in window;
  var $$ = function(s, r){ return Array.prototype.slice.call((r || document).querySelectorAll(s)); };
  var num = function(el, a, d){ var v = parseFloat(el.getAttribute(a)); return isFinite(v) ? v : d; };
  function layer(el, cls){
    var s = el.querySelector(':scope > .' + cls);
    if (!s){ s = document.createElement('span'); s.className = cls; s.setAttribute('aria-hidden', 'true'); el.appendChild(s); }
    if (getComputedStyle(el).position === 'static') el.style.position = 'relative';
    return s;
  }
  function onView(els, fn){
    if (!io){ els.forEach(fn); return; }
    var ob = new IntersectionObserver(function(es){ es.forEach(function(e){ if (e.isIntersecting){ ob.unobserve(e.target); fn(e.target); } }); }, { rootMargin: '0px 0px -50px 0px' });
    els.forEach(function(el){ ob.observe(el); });
  }
  function onScroll(fn){
    var busy = false;
    var run = function(){ busy = false; fn(); };
    addEventListener('scroll', function(){ if (!busy){ busy = true; requestAnimationFrame(run); } }, { passive: true });
    addEventListener('resize', run);
    fn();
  }
  // Add a transition without dropping the element's own (the outline buttons' colour wipe, for example).
  function addTransition(el, t){
    var base = getComputedStyle(el).transition;
    el.style.transition = (base && !/^all 0s/.test(base) ? base + ', ' : '') + t;
  }
  // Hide an element (blur + fade + offset) and bring it back when it scrolls into view.
  function hide(el, blur, move, dur, ease, delay){
    if (getComputedStyle(el).display === 'inline') el.style.display = 'inline-block';
    var t = dur + 's ' + ease + ' ' + delay + 's';
    addTransition(el, 'opacity ' + t + ', filter ' + t + ', translate ' + t);
    el.style.opacity = '0'; el.style.filter = 'blur(' + blur + 'px)'; el.style.translate = move;
  }
  function show(el){ el.style.opacity = ''; el.style.filter = ''; el.style.translate = ''; }

  // Magic UI: Border Beam, Shine Border (decorative layers)
  $$('.mu-beam').forEach(function(el){ layer(el, 'mu-beam-ray'); });
  $$('.mu-shine').forEach(function(el){ layer(el, 'mu-shine-ray'); });

  // Magic UI: Marquee (clones the track; the copies are hidden from assistive tech and keyboard)
  if (!reduce) $$('.mu-marquee').forEach(function(el){
    var track = el.querySelector('.mu-marquee-track');
    if (!track) return;
    for (var i = 1, n = num(el, 'data-repeat', 4); i < n; i++){
      var c = track.cloneNode(true);
      c.setAttribute('aria-hidden', 'true');
      $$('a, button', c).forEach(function(a){ a.tabIndex = -1; });
      el.appendChild(c);
    }
    el.classList.add('is-ready');
  });

  // Magic UI: Scroll Progress
  var bars = $$('.mu-progress');
  if (bars.length) onScroll(function(){
    var max = document.documentElement.scrollHeight - innerHeight;
    var p = max > 0 ? Math.min(1, Math.max(0, scrollY / max)) : 0;
    bars.forEach(function(b){ b.style.transform = 'scaleX(' + p.toFixed(4) + ')'; });
  });

  // Magic UI: Number Ticker (counts to the number already in the text; ends on the original text exactly)
  if (!reduce) $$('[data-mu-ticker]').forEach(function(el){
    if (el.children.length) return;
    var txt = el.textContent, m = txt.match(/\\d[\\d,]*(\\.\\d+)?/);
    if (!m) return;
    var target = parseFloat(m[0].replace(/,/g, '')), dec = m[1] ? m[1].length - 1 : 0, grouped = m[0].indexOf(',') > -1;
    var start = num(el, 'data-start', 0), dur = num(el, 'data-duration', 1.6) * 1000;
    if (!isFinite(target)) return;
    var pre = txt.slice(0, m.index), post = txt.slice(m.index + m[0].length);
    var fmt = function(v){
      var s = v.toFixed(dec);
      if (grouped){ var p = s.split('.'); p[0] = p[0].replace(/\\B(?=(\\d{3})+(?!\\d))/g, ','); s = p.join('.'); }
      return pre + s + post;
    };
    el.style.fontVariantNumeric = 'tabular-nums';
    el.textContent = fmt(start);
    onView([el], function(){
      var t0 = null;
      var step = function(t){
        if (t0 === null) t0 = t;
        var k = Math.min(1, (t - t0) / dur);
        el.textContent = k < 1 ? fmt(start + (target - start) * (1 - Math.pow(1 - k, 4))) : txt;
        if (k < 1) requestAnimationFrame(step);
      };
      requestAnimationFrame(step);
    });
  });

  if (!reduce && io){
    // Magic UI: Blur Fade
    $$('[data-mu-blur-fade]').forEach(function(el){
      var o = num(el, 'data-offset', 6), d = el.getAttribute('data-direction') || 'down';
      var move = d === 'up' ? '0 ' + o + 'px' : d === 'left' ? o + 'px 0' : d === 'right' ? -o + 'px 0' : '0 ' + -o + 'px';
      hide(el, 6, move, 0.4, 'ease-out', 0.04 + num(el, 'data-delay', 0));
    });
    onView($$('[data-mu-blur-fade]'), show);

    // Smooth UI: Shimmer Sweep
    $$('[data-su-sweep]').forEach(function(el){ hide(el, 8, '-22px 0', 0.85, 'cubic-bezier(.22,1,.36,1)', num(el, 'data-delay', 0)); });
    onView($$('[data-su-sweep]'), show);

    // Smooth UI: Mask Reveal Up (lines split at <br>)
    $$('[data-su-mask-reveal]').forEach(function(el){
      var lines = [[]];
      Array.prototype.slice.call(el.childNodes).forEach(function(n){
        if (n.nodeName === 'BR'){ lines.push([]); el.removeChild(n); } else lines[lines.length - 1].push(n);
      });
      var base = num(el, 'data-delay', 0), stagger = num(el, 'data-stagger', 90) / 1000;
      // Lines are blocks, so the <br> becomes a space: the text still reads as words to assistive tech.
      var inners = lines.filter(function(l){ return l.length; }).map(function(l, i, all){
        if (i < all.length - 1) l.push(document.createTextNode(' '));
        var outer = document.createElement('span'), inner = document.createElement('span');
        outer.className = 'su-mask'; inner.className = 'su-mask-in';
        l.forEach(function(n){ inner.appendChild(n); });
        outer.appendChild(inner); el.appendChild(outer);
        hide(inner, 6, '0 30px', 0.76, 'cubic-bezier(.22,1,.36,1)', base + i * stagger);
        return inner;
      });
      onView([el], function(){ inners.forEach(show); });
    });
  }

  // Smooth UI: Scroll Reveal Paragraph (words light up with scroll)
  var paras = reduce ? [] : $$('[data-su-scroll-reveal]').map(function(p){
    var words = [];
    (function walk(n){
      Array.prototype.slice.call(n.childNodes).forEach(function(c){
        if (c.nodeType === 1) return walk(c);
        if (c.nodeType !== 3) return;
        var f = document.createDocumentFragment();
        c.textContent.split(/(\\s+)/).forEach(function(w){
          if (!w) return;
          if (/^\\s+$/.test(w)) return f.appendChild(document.createTextNode(w));
          var s = document.createElement('span'); s.className = 'su-word'; s.textContent = w; words.push(s); f.appendChild(s);
        });
        n.replaceChild(f, c);
      });
    })(p);
    return { p: p, w: words };
  });
  if (paras.length) onScroll(function(){
    var vh = innerHeight;
    paras.forEach(function(it){
      var pr = Math.max(0, Math.min(1, (vh * 0.9 - it.p.getBoundingClientRect().top) / (vh * 0.65))), n = it.w.length;
      it.w.forEach(function(s, i){ s.style.opacity = String(0.18 + 0.82 * Math.max(0, Math.min(1, pr * n - i))); });
    });
  });

  if (!hover || reduce) return;

  // Magic UI: Magic Card (spotlight)
  $$('.mu-spotlight').forEach(function(c){
    layer(c, 'mu-spot');
    c.addEventListener('pointermove', function(e){
      var r = c.getBoundingClientRect();
      c.style.setProperty('--mx', (e.clientX - r.left) + 'px'); c.style.setProperty('--my', (e.clientY - r.top) + 'px');
      c.classList.add('is-lit');
    });
    c.addEventListener('pointerleave', function(){ c.classList.remove('is-lit'); });
  });

  // Smooth UI: Glow Hover Cards
  $$('[data-su-glow]').forEach(function(g){
    var kids = Array.prototype.slice.call(g.children);
    kids.forEach(function(k){ layer(k, 'su-glow-ray'); });
    g.addEventListener('pointermove', function(e){
      kids.forEach(function(k){ var r = k.getBoundingClientRect(); k.style.setProperty('--gx', (e.clientX - r.left) + 'px'); k.style.setProperty('--gy', (e.clientY - r.top) + 'px'); });
      g.style.setProperty('--glow-on', '1');
    });
    g.addEventListener('pointerleave', function(){ g.style.setProperty('--glow-on', '0'); });
  });

  // Smooth UI: Tilt Card
  $$('[data-su-tilt]').forEach(function(c){
    var max = num(c, 'data-tilt-max', 8), glare = layer(c, 'su-glare'), depth = $$('[data-tilt-depth]', c);
    addTransition(c, 'transform .25s ease-out');
    c.addEventListener('pointermove', function(e){
      var r = c.getBoundingClientRect(), nx = (e.clientX - r.left) / r.width * 2 - 1, ny = (e.clientY - r.top) / r.height * 2 - 1;
      c.style.transform = 'perspective(900px) rotateX(' + (-ny * max).toFixed(2) + 'deg) rotateY(' + (nx * max).toFixed(2) + 'deg) scale(1.03)';
      glare.style.opacity = '1';
      glare.style.background = 'radial-gradient(circle at ' + ((nx + 1) * 50).toFixed(1) + '% ' + ((ny + 1) * 50).toFixed(1) + '%, rgba(255,255,255,.18), transparent 60%)';
      depth.forEach(function(d){ var k = Math.min(1, Math.max(0, num(d, 'data-tilt-depth', 0))); d.style.translate = (nx * k * 24).toFixed(1) + 'px ' + (ny * k * 24).toFixed(1) + 'px'; });
    });
    c.addEventListener('pointerleave', function(){ c.style.transform = ''; glare.style.opacity = '0'; depth.forEach(function(d){ d.style.translate = ''; }); });
  });

  // Smooth UI: Magnetic Button
  var mags = $$('[data-su-magnetic]'), pt = null, busy = false;
  mags.forEach(function(m){ addTransition(m, 'translate .4s cubic-bezier(.2,.8,.2,1.1)'); });
  var pull = function(){
    busy = false;
    mags.forEach(function(m){
      var r = m.getBoundingClientRect(), dx = pt.x - (r.left + r.width / 2), dy = pt.y - (r.top + r.height / 2);
      var s = num(m, 'data-strength', 0.25), near = Math.hypot(dx, dy) < num(m, 'data-radius', 100) + Math.max(r.width, r.height) / 2;
      m.style.translate = near ? (dx * s).toFixed(1) + 'px ' + (dy * s).toFixed(1) + 'px' : '';
    });
  };
  if (mags.length){
    document.addEventListener('pointermove', function(e){ pt = { x: e.clientX, y: e.clientY }; if (!busy){ busy = true; requestAnimationFrame(pull); } }, { passive: true });
    document.documentElement.addEventListener('pointerleave', function(){ mags.forEach(function(m){ m.style.translate = ''; }); });
  }

  // 21st.dev-style: Background Paths (fine accent lines drifting along their curves)
  $$('.tw-paths').forEach(function(el){
    if (el.firstChild) return;
    var host = el.parentElement;
    if (host && getComputedStyle(host).position === 'static') host.style.position = 'relative';
    if (host && getComputedStyle(host).overflow === 'visible') host.style.overflow = 'hidden';
    var n = Math.min(40, Math.max(4, num(el, 'data-lines', 18))), out = '';
    for (var i = 0; i < n; i++){
      var y = 30 + i * (340 / n), dash = 260 + (i * 37) % 240;
      out += '<path pathLength="1000" stroke-width="' + (0.5 + i * 0.04).toFixed(2) + '" stroke-opacity="' + (0.06 + i * 0.012).toFixed(3) + '"'
        + ' stroke-dasharray="' + dash + ' ' + (1000 - dash) + '" style="--d:' + (18 + (i * 7) % 14) + 's;animation-delay:-' + ((i * 1.7) % 12).toFixed(1) + 's"'
        + ' d="M-60 ' + y.toFixed(1) + ' C 240 ' + (y - 130 + i * 4).toFixed(1) + ', 620 ' + (y + 150 - i * 3).toFixed(1) + ', 1060 ' + (y - 50).toFixed(1) + '"/>';
    }
    el.innerHTML = '<svg viewBox="0 0 1000 400" preserveAspectRatio="none" focusable="false">' + out + '</svg>';
  });

  // 21st.dev-style: Scroll Media Expansion (the frame opens from an inset, rounded card to full width)
  var ex = $$('.tw-expand');
  if (ex.length && !reduce) onScroll(function(){
    var h = innerHeight;
    ex.forEach(function(el){
      var r = el.getBoundingClientRect();
      if (r.bottom < -h || r.top > h * 2) return;
      var e = 1 - Math.pow(1 - Math.min(1, Math.max(0, (h - r.top) / (h * 0.9))), 2), q = 1 - e;
      var f = el.querySelector('.tw-expand-frame'), im = f && f.querySelector('img');
      if (f) f.style.clipPath = 'inset(' + (q * 12).toFixed(2) + '% ' + (q * 20).toFixed(2) + '% round ' + (q * 28).toFixed(1) + 'px)';
      if (im) im.style.scale = (1.18 - 0.18 * e).toFixed(4);
    });
  });
})();`;
